version: 2.1

orbs:
  demotest: nikita/demotest@1.0.1

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - demotest/qualys:
          platformurl: https://qualysguard.qg1.apps.qualys.ca/ 
          username: quays_ds 
          password: wR67EStont 

workflows:
  example-workflow:
    jobs:
      - example-job
