version: 2.1
orbs:
 nikita:nikita/demo@1.0.0
jobs:
  lint:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - nikita/lint
  test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - nikita/test
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "Build docker image"
          command: echo "image sucessfully built"
      - run:
          name: "Publish image"
          command: echo "image successfully published"
  deploy:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "Deploy image using----"
          command: echo "image succesfully deployed"
workflows:
  test-and-deploy:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
