version: 2.1
orbs:
  nikita: nikita/demotest@1.0.0
jobs:
  scanjob:
    docker:
      - image: "cimg/base:stable"
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - nikita/demotest: # invoke command "sayhello"
          to: "Lev"
commands:
  scan:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - nikita/demotest:  << parameters.to >>


workflows:
  nikita/sayhello:
    jobs:
      - scanjob


